services:
  - type: web
    name: stardust-api
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build:api
    startCommand: npm run start:api
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MVX_NETWORK
        value: devnet
      - key: MVX_CHAIN_ID
        value: D
      - key: MVX_API_URL
        value: https://devnet-api.multiversx.com
      - key: MVX_GATEWAY_URL
        value: https://devnet-gateway.multiversx.com
      - key: MONGODB_URI
        sync: false
      - key: PINATA_API_KEY
        sync: false
      - key: PINATA_SECRET_KEY
        sync: false
      - key: GAME_CONTRACT_ADDRESS
        sync: false
      - key: NFT_COLLECTION_TICKER
        value: SDST-123456
      - key: REDIS_URL
        sync: false
    disk:
      name: stardust-storage
      mountPath: /opt/render/project/src/storage
      sizeGB: 1

  - type: static_site
    name: stardust-frontend
    buildCommand: npm ci && npm run build:frontend
    publishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://stardust-api.onrender.com
      - key: VITE_MVX_NETWORK
        value: devnet
      - key: VITE_WALLET_CONNECT_PROJECT_ID
        sync: false

databases:
  - name: stardust-mongodb
    databaseName: stardust_gaming
    user: stardust_user
    plan: free
    region: frankfurt
