[package]
name = "stardust-contracts-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.stardust-contracts]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.59.0"
default-features = false
